### ISSUE TITLE
Filter returned data by realm ID

### ISSUE THREAD

**Issue by brucetony** [PrivateAIM/node-ui#65]
Need to limit the returned data to only those for that specific realm/location. This requires knowing the UUID of the realm and using that to filter the fetch requests e.g. `https://privateaim.net/core/analyses?include=project,master_image&filter[realm_id]=90910ba4-67fa-4548-be02-c5b9e0aed805`

**Comment by tada5hi** [comment]
Get Analysis-Node relations for Node.
1.1 `https://privateaim.net/core/analysis-nodes?filter[node_id]=xxx`
1.2 `https://privateaim.net/core/analysis-nodes?filter[node_realm_id]=xxx`

Get Analysis for ids:
2. `https://privateaim.net/core/analyses?filter[id]=xxx,yyy,zzz,...`

**Comment by brucetony** [comment]
This issue has been offloaded to the Hub Adapter: https://github.com/PrivateAIM/node-hub-api-adapter/issues/12
