### ISSUE TITLE
Retrieve results from hub

### ISSUE THREAD

**Issue by brucetony** [PrivateAIM/node-ui#72]
Current `ObjectDownloadButton` component can only retrieve local objects from minio. Need to generalize this component so hub object retrieval is possible as well as integrate these buttons in the UI

- [x] Generalize `ObjectDownloadButton` so local/remote can be toggled
- [ ] Integrate components in UI

**Comment by brucetony** [comment]
Not sure if this is a necessary feature for the Node UI

**Comment by tada5hi** [comment]
+1 
The decision is properly affected/influenced by the upcoming security concept.

**Comment by brucetony** [comment]
It was decided that the results will accessed solely through the hub
