### ISSUE TITLE
Authorization loop when sending approval/rejection

### ISSUE THREAD

**Issue by brucetony** [PrivateAIM/node-ui#86]
If the provided robot credentials does not have the permission for approving/rejecting either an analysis or project, then the Hub sends back a 403 response and the middleware catches this and believes it is due to the user not being signed in. Need to improve the middleware to first check if the user is signed in, and if so, then return a toast/console message indicating the authorization issue.

Related to #67

**Comment by tada5hi** [comment]
401 should be the status code signalising that the entity is not authenticated
403 is an error due the lack of sufficient (authorization) permissions

**Comment by brucetony** [comment]
The issue was with the non-admin robot permissions on the hub side.  Robots will now be given `project_approve` and `analysis_approve` permissions when created which will allow them to send the approval updates
